import 'assistant.dart';

/// Returned once after `createAssistant` — same as [Assistant] but carries
/// the one-time generated password. The backend never returns it again after
/// this initial provisioning response.
class ProvisionedAssistant extends Assistant {
  const ProvisionedAssistant({
    required super.id,
    required super.phone,
    required super.displayName,
    required super.status,
    required super.createdAt,
    super.title,
    super.subtitle,
    super.clinicBranchIds,
    required this.generatedPassword,
  });

  /// The one-time plain-text password generated by the backend (or mock).
  /// Must be shown to the Doctor immediately and never stored client-side.
  final String generatedPassword;

  /// Downcast to [Assistant] for storage in the list after credential display.
  Assistant toAssistant() => Assistant(
    id: id,
    phone: phone,
    displayName: displayName,
    status: status,
    createdAt: createdAt,
    title: title,
    subtitle: subtitle,
    clinicBranchIds: clinicBranchIds,
  );
}
