// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_nkC-l4fl3UyXRYPk-qRtgaY5-1MTlU',
    appId: '1:221476713418:web:bb21f43fd270cdf6de5533',
    messagingSenderId: '221476713418',
    projectId: 'clinic-dd7cc',
    authDomain: 'clinic-dd7cc.firebaseapp.com',
    storageBucket: 'clinic-dd7cc.firebasestorage.app',
    measurementId: 'G-KGB7XVZ00E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaLciv25JLVo2dZGnznSoe1ulwlv8NZw0',
    appId: '1:221476713418:android:7380377d862cb824de5533',
    messagingSenderId: '221476713418',
    projectId: 'clinic-dd7cc',
    storageBucket: 'clinic-dd7cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh7hdBgB8y_W6ia8xKczUiLh06f3_x8Rs',
    appId: '1:221476713418:ios:a0dec8b21cd4f83dde5533',
    messagingSenderId: '221476713418',
    projectId: 'clinic-dd7cc',
    storageBucket: 'clinic-dd7cc.firebasestorage.app',
    iosBundleId: 'com.medsuper.medSuper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV_nkC-l4fl3UyXRYPk-qRtgaY5-1MTlU',
    appId: '1:221476713418:web:684291f776366498de5533',
    messagingSenderId: '221476713418',
    projectId: 'clinic-dd7cc',
    authDomain: 'clinic-dd7cc.firebaseapp.com',
    storageBucket: 'clinic-dd7cc.firebasestorage.app',
    measurementId: 'G-RBPT16QWXB',
  );
}
